### PR TITLE
Add type definitions for TypeScript consumers

### PR DESCRIPTION
**Pull request by ghost**
The type definitions I wrote should be comprehensive.
However, the types do need checking by someone more familiar with the repository.

### CODE REVIEW

**Comment by rstacruz** [comment]
Whoa that's awesome! Thanks for this! I wonder if it makes sense to add some tests, such as [this one](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express/express-tests.ts) for the types in `@types/express`. I don't remember the API very well to really review this myself, so some sort of automation to make this maintainable would be very welcome.

[ts-expect](https://github.com/TypeStrong/ts-expect) is also worth a look, tho I haven't tried either one yet.

**Comment by ghost** [comment]
Sorry wrong repo lol

**Comment by ghost** [comment]
I'll add tests tomorrow, working on jashkenas / coffeescript type definitions right now

**Comment by ghost** [comment]
🤔 Maybe it would be better to do this over at DefinitelyTyped and go for separation of concerns. (E.g. updating types means incrementing the library version if this PR merges.)

**Comment by rstacruz** [comment]
Absolutely, thats a good place for it! Here or there is fine in any case.

**Comment by ghost** [comment]
Resolved in DefinitelyTyped/DefinitelyTyped#55590

**Pull request closed without merging**
