### PR TITLE
Misc bug fixes

### PR DESCRIPTION
**Pull request by rianhunter**
Some bug fixes with code generation and ast generation.

For the "BlockStatement" commit, my observation is that this is yet another special case of checking for node type "BlockStatement." From what I can tell, this is because the code is structured so that the container nodes are responsible for outputting the indent. If the code was instead structured so that the code that emits statements was responsible for the indent, there would be no special cases and the code would be simpler. Something to think about for the future.

### CODE REVIEW

**Comment by rstacruz** [comment]
oops... sorry i missed seeing this. this looks important. any chances for some tests?

**Comment by rianhunter** [comment]
Yeah these are all actually pretty serious / glaring bugs. I can add tests for each bug.

**Comment by rianhunter** [comment]
Okay added tests for each broken bug. The tests do a string-comparison against expected outcome. This may cause these tests to generate false positives in the future though I wasn't sure of a better way to add tests for code generation.

**Comment by rstacruz** [comment]
a little late for the party, but i sweaaar i'll look at this soon >_<

**Comment by rianhunter** [comment]
Ping! These are pretty serious bugs.

**Comment by rstacruz** [comment]
Okay, merged, 2.2.0 is out and the website has been updated. Sorry this took a while, stepped away from js2coffee for a bit there.

**Pull request merged**
